// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo8CZj8a73I59SgvSziGCbq4mW5MCMMVU',
    appId: '1:817551514717:web:1859f245828dd6c27d01b4',
    messagingSenderId: '817551514717',
    projectId: 'kabutor-689cc',
    authDomain: 'kabutor-689cc.firebaseapp.com',
    storageBucket: 'kabutor-689cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOw2xHz2D-FvJ309sZ81vRBy-0ka6Cjmo',
    appId: '1:817551514717:android:ac727e3f01445db87d01b4',
    messagingSenderId: '817551514717',
    projectId: 'kabutor-689cc',
    storageBucket: 'kabutor-689cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF4P2c0R1MwuHZBRx9BSXtWwL4q8P6ATg',
    appId: '1:817551514717:ios:bde5fed6fc96b2a57d01b4',
    messagingSenderId: '817551514717',
    projectId: 'kabutor-689cc',
    storageBucket: 'kabutor-689cc.appspot.com',
    iosClientId: '817551514717-p1f82a4jtivni4t0fapim7kqq0bugedu.apps.googleusercontent.com',
    iosBundleId: 'com.oxsmic.kabutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF4P2c0R1MwuHZBRx9BSXtWwL4q8P6ATg',
    appId: '1:817551514717:ios:bde5fed6fc96b2a57d01b4',
    messagingSenderId: '817551514717',
    projectId: 'kabutor-689cc',
    storageBucket: 'kabutor-689cc.appspot.com',
    iosClientId: '817551514717-p1f82a4jtivni4t0fapim7kqq0bugedu.apps.googleusercontent.com',
    iosBundleId: 'com.oxsmic.kabutor',
  );
}
